baseurl = "https://blog.yuri-k.com"
languageCode = "zh-cmn-Hant"
title = "Bingo"
theme = "hugo-bingo"

disableHugoGeneratorInject = true
enableEmoji = true
footnoteReturnLinkContents = "↩"
hasCJKLanguage = true
googleAnalytics = "UA-123-45"



[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "post"
    name = "Posts"
    url = "/post"
    weight = 20

[params]
  email = "username@domain"
  github = "github_username"
  linkedin = "linkedin_username"
  medium = "medium_username"
  twitter = "twitter_username"
  facebook = "facebook_username"
  instagram = "instagram_username"
